name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        nvim_version: [nightly, stable]
    env:
      NVIM_RELEASE_URL: https://github.com/neovim/neovim/releases/download/${{ matrix.nvim_version }}/nvim-linux64.tar.gz
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y fd-find mlocate

          mkdir nvim
          echo "Downloading $NVIM_RELEASE_URL..."
          curl -sL $NVIM_RELEASE_URL | tar -zxf - --strip-components=1 -C nvim

      - name: Download plugins
        run: |
          NVIM_PLUGIN_PATH=~/.local/share/nvim/site/pack/vendor/start
          mkdir -p $NVIM_PLUGIN_PATH
          ln -s $(pwd) $NVIM_PLUGIN_PATH

          cd $NVIM_PLUGIN_PATH
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim
          git clone --depth 1 https://github.com/nvim-telescope/telescope.nvim

      - name: Run tests
        run: |
          export PATH="$(pwd)/nvim/bin:$PATH"
          make test

  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

      - name: Lint
        run: make lint

  check_style:
    name: check style
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          args: --color always --check lua/
